### ISSUE TITLE
Did not matches the lowest prices

### ISSUE THREAD

**Issue by darius71** [TheFes/cheapest-energy-hours#128]
I am new on Home Assitant. 

Automation do not work cheapest according cheapest prices:

1. Triggered by the state of binary_sensor.maziausia_kaina at February 22, 2024 at 10:05:36. Toggle Gyvatukas Ia Socket
(switch.gyvatukas_ia_socket) turned on.
2. Triggered by the state of binary_sensor.maziausia_kaina at February 22, 2024 at 17:52:42. Toggle Gyvatukas Ia Socket
(switch.gyvatukas_ia_socket) turned off

After that, sensor did not triggered at all...

Automation:
```yaml
alias: Jungiam gyvatukus
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.maziausia_kaina
    to:
      - "on"
      - "off"
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: switch.gyvatukas_ia_socket
        state: "{{ states(\"binary_sensor.maziausia_kaina\") }}"
action:
  - type: toggle
    device_id: 5bc4d17541b8b9edac6813674d5a95f0
    entity_id: switch.gyvatukas_ia_socket
    domain: switch
mode: single
```
Template:
```yaml
binary_sensor:
  name: maziausia kaina
  unique_id: d4d8b8b6-66fa-4be8-872d-5fd0218bc842
  state: >
    {% set n = now() %}
    {% set sensor = 'sensor.energy_prices' -%}
    {% from 'cheapest_energy_hours.jinja' import cheapest_energy_hours %}
    {{ cheapest_energy_hours(sensor=sensor, hours=2, split=true, include_tomorrow=false, mode="is_now") }}
```

Have any ideas?

Thank you

**Comment by TheFes** [comment]
Please add code tags around the yaml code to make it readable.

**Comment by TheFes** [comment]
Can you put this in developer tools > template
```
{% set n = now() %}
{% set sensor = 'sensor.energy_prices' -%}
{% from 'cheapest_energy_hours.jinja' import cheapest_energy_hours %}
{{ cheapest_energy_hours(sensor=sensor, hours=2, split=true, include_tomorrow=false, mode="all") }}
```

It will show you when the time blocks are when the price is lowest, and thus, when the binary sensor should be `on`

**Comment by darius71** [comment]
Result of developer tool:
[{"start":"2024-02-23T00:00:00+02:00","end":"2024-02-23T01:00:00+02:00","hours":1.0,"prices":[0.0049],"is_now":false},{"total_hours":2.0,"datapoints_per_hour":1,"datapoints":2}

But no action at "2024-02-23T00:00:00+02:00"

**Comment by TheFes** [comment]
Did you already create this binary sensor yesterday?

**Comment by TheFes** [comment]
wait, can you have a look at the history of the binary sensor? Was it `on` between 00:00 and 02:00 last night?

**Comment by TheFes** [comment]
The problem is most probably in your condition. State conditions don't accept templates.
Use a template condition instead
```yaml
alias: Jungiam gyvatukus
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.maziausia_kaina
    to:
      - "on"
      - "off"
condition:
  - condition: state
     value_template: "{{ states('switch.gyvatukas_ia_socket') != states('binary_sensor.maziausia_kaina') }}"
action:
  - service: switch.toggle
    target:
      entity_id: switch.gyvatukas_ia_socket
mode: single
```

**Comment by TheFes** [comment]
You can also do it without the condition:
```
alias: Jungiam gyvatukus
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.maziausia_kaina
    to:
      - "on"
      - "off"
action:
  - service: switch.turn_{{ trigger.to_state.state }}
    target:
      entity_id: switch.gyvatukas_ia_socket
mode: single
```
