### ISSUE TITLE
Gone through documentation but unsure how I get output

### ISSUE THREAD

**Issue by markbrewster** [TheFes/cheapest-energy-hours#161]
I've been through documentation for hours and have tried asking chatgpt etc but still have problems getting this working! Any help would be amazing. I am just starting out with home assistant so please bear with me.

I am using nordpool for prices and the sensor outputs as expected when added to dashboard. I have added CEH via HACS just like I added nordpool integration.

However - the examples for the sensor in documentation, I am assuming I put these in configuration.yaml? I have added a sensor like this:

```yaml
template:
  - sensor:
      - name: "Cheapest Hour Test"
        unique_id: "cheapest_hour_test"
        state: >
          {% set n = now() %}
          {% from 'cheapest_energy_hours.jinja' import cheapest_energy_hours %}
          {% set output = cheapest_energy_hours(sensor='sensor.nordpool', attr_today='forecast_today', attr_tomorrow='prices_tomorrow', time_key='datetime', value_key='value') %}
```
...but I get nothing output. As you can see my nordpool sensor has been added fine to dashboard, below the nordpool sensor test, but nothing gets output:
![image](https://github.com/user-attachments/assets/b359d157-b788-4e26-87c0-3f1f22b5cffc)

I can't see anything of significance in the logs either:
![image](https://github.com/user-attachments/assets/b5d7cf22-1482-4514-9daa-3bb6c0f78a52)

Any help would be appreciated!

**Comment by TheFes** [comment]
There is no need to provide all these additional parameters if you use Nordpool, as I originally built it based on that integration.
There is also no need to add a reference to `now()` it will automatically update when `sensor.nordpool` changes.
Furthermore you were not outputting anything. You were setting an `ouput` variable but you were not outputting it.

So this should work (you can test it in developer tools > template)
```
template:
  - sensor:
      - name: "Cheapest Hour Test"
        unique_id: "cheapest_hour_test"
        state: >
          {% from 'cheapest_energy_hours.jinja' import cheapest_energy_hours %}
          {{ cheapest_energy_hours(sensor='sensor.nordpool') }}
```
