### ISSUE TITLE
Tibber and I am not getting the sample code from the documentation to work

### ISSUE THREAD

**Issue by rafdev18** [TheFes/cheapest-energy-hours#162]
Hi TheFes,

I am lost - when I try your tibber sample code I am simply told this is not a sensor code. For me the sample looks like to is a combination of code which should go to my configuration.yaml and the rest into the automation.yaml.

I am really stuck -

* trigger and action are only available in an automation
* sensor should be defined in the config for HA
* I have the right tibber integration installed and it populates the right sensors BUT there is no timber.get_prices service

I did quite some stuff on HA - heat pump, solar, car, ... everything is working ... the code in this documentation is just a mystery for me ... maybe it is my skill level ... tx for any help !

```yaml
template:
  - trigger:
      - platform: time_pattern
        hours: "/1"
      - platform: homeassistant
        event: start
    action:
      - service: tibber.get_prices
        data:
          start: "{{ (today_at() - timedelta(days=1)).strftime('%Y-%m-%d %H:%M:%S') }}"
          end: "{{ (today_at() + timedelta(days=2)).strftime('%Y-%m-%d %H:%M:%S') }}"
        response_variable: prices
    sensor:
      - unique_id: 79c470d8-4ccd-4f44-b3a2-e3d59d5dda8a
        name: Tibber prices
        state: "{{ prices.prices.values() | first | selectattr('start_time', '<=', now()) | map(attribute='price') | list | last }}"
        attributes:
          prices: >
            {% set ns = namespace(prices=[]) %}
            {% for i in prices.prices.values() | first %}
              {% set n = dict(start_time = i.start_time.isoformat(), price = i.price) %}
              {% set ns.prices = ns.prices + [n] %}
            {% endfor %}
            {{ ns.prices }}
```
