### ISSUE TITLE
No valid sensor found

### ISSUE THREAD

**Issue by froggi1930** [TheFes/cheapest-energy-hours#170]
Since two days I can not process the data anymore...

```javascript
{% from 'cheapest_energy_hours.jinja' import cheapest_energy_hours %}
{% set output = cheapest_energy_hours(sensor='sensor.tibber_forecast', hours=6,mode = 'all') %}
{{output}}
``` 
will result in:
error: No valid sensor found

The template has not been changed:
```javascript
template:
  - trigger:
      - platform: time_pattern
        hours: "/1"
      - platform: homeassistant
        event: start
    action:
      - service: tibber.get_prices
        data:
          start: "{{ (today_at() - timedelta(days=1)).strftime('%Y-%m-%d %H:%M:%S') }}"
          end: "{{ (today_at() + timedelta(days=2)).strftime('%Y-%m-%d %H:%M:%S') }}"
        response_variable: prices
    sensor:
      - name: tibber_forecast
        state: "{{ prices.prices.values() | first | selectattr('start_time', '<=', now()) | map(attribute='price') | list | last }}"
        attributes:
          prices: >
            {% set ns = namespace(prices=[]) %}
            {% for i in prices.prices.values() | first %}
              {% set n = dict(start_time = i.start_time.isoformat(), price = i.price) %}
              {% set ns.prices = ns.prices + [n] %}
            {% endfor %}
            {{ ns.prices }}
``` 

anybody else with this problem?

**Comment by froggi1930** [comment]
yes I am on 2024.11.0b5 right now

**Comment by froggi1930** [comment]
Log files says...

Logger: homeassistant.helpers.sensor
Quelle: helpers/trigger_template_entity.py:204
Erstmals aufgetreten: 19:12:46 (1 Vorkommnisse)
Zuletzt protokolliert: 19:12:46

Error rendering state template for sensor.tibber_forecast: TypeError: '<=' not supported between instances of 'str' and 'datetime.datetime'

**Comment by TheFes** [comment]
Yeah, I know what's wrong. Need to update the docimentation on this. 
Try:
```
template:
  - trigger:
      - platform: time_pattern
        hours: "/1"
      - platform: homeassistant
        event: start
    action:
      - service: tibber.get_prices
        data:
          start: "{{ (today_at() - timedelta(days=1)).strftime('%Y-%m-%d %H:%M:%S') }}"
          end: "{{ (today_at() + timedelta(days=2)).strftime('%Y-%m-%d %H:%M:%S') }}"
        response_variable: prices
    sensor:
      - name: tibber_forecast
        state: "{{ prices.prices.values() | first | selectattr('start_time', '<=', utcnow().isoformat()) | map(attribute='price') | list | last }}"
        attributes:
          prices: >
            {% set ns = namespace(prices=[]) %}
            {% for i in prices.prices.values() | first %}
              {% set n = dict(start_time = i.start_time.isoformat(), price = i.price) %}
              {% set ns.prices = ns.prices + [n] %}
            {% endfor %}
            {{ ns.prices }}
```
