### ISSUE TITLE
"String does not match the pattern of "Legacy_Syntax" in code example

### ISSUE THREAD

**Issue by Marty56** [TheFes/cheapest-energy-hours#177]
I am trying to use the code snipplet for the price sensor (tibber example)
```
template:
  - trigger:
      - alias: Triggers every hour
        platform: time_pattern
        hours: "/1"
      - alias: Triggers on home assistant startup
        platform: homeassistant
        event: start
```

The part "platform: time_pattern" is flagged with an error stating "String does not match the pattern of "Legacy_Syntax"
