### ISSUE TITLE
Tibber sensor

### ISSUE THREAD

**Issue by vincentbitter** [TheFes/cheapest-energy-hours#188]
Hi,

Thanks for all your effort creating this plugin for Home Assistant. I started setting up this tool, but had a lot of issues getting the sensor for Tibber up and running. It seems like the script in the [documentation](https://github.com/TheFes/cheapest-energy-hours/blob/V5.5.4/documentation/1-source_sensor.md#tibber) is outdated.

```yaml
template:
  - trigger:
      - platform: time_pattern
        hours: "/1"
      - platform: homeassistant
        event: start
    action:
      - service: tibber.get_prices
        data:
          start: "{{ (today_at() - timedelta(days=1)).strftime('%Y-%m-%d %H:%M:%S') }}"
          end: "{{ (today_at() + timedelta(days=2)).strftime('%Y-%m-%d %H:%M:%S') }}"
        response_variable: prices
    sensor:
      - unique_id: 79c470d8-4ccd-4f44-b3a2-e3d59d5dda8a
        name: Tibber prices
        state: "{{ prices.prices.values() | first | selectattr('start_time', '<=', now()) | map(attribute='price') | list | last }}"
        attributes:
          prices: >
            {% set ns = namespace(prices=[]) %}
            {% for i in prices.prices.values() | first %}
              {% set n = dict(start_time = i.start_time.isoformat(), price = i.price) %}
              {% set ns.prices = ns.prices + [n] %}
            {% endfor %}
            {{ ns.prices }}
```

The 'start_time' is a string, so `selectattr('start_time', '<=', now())` seems to fail. I adjusted it to:
```yaml
        state: "{{ prices.prices.values() | first | selectattr('start_time', '==', now().strftime('%Y-%m-%dT%H:00:00.000+01:00')) | map(attribute='price') | list | last | float }}"
```
_Note: I hardcoded the timezone in the equation, as I couldn't figure out how to convert the server time to the Tibber timezone. In my case the server timezone is the same as Tibber, so works for me._

The same issue appeared in the sensor, as you cannot call `.isoformat()` on a string. I changed that to `as_datetime(i.start_time).isoformat()`.

I also added the price level (LOW/MEDIUM/HIGH), an icon for the sensor, and changed the unique_id to something that makes sense. 

```yaml
template:
  - trigger:
      - platform: time_pattern
        hours: "/1"
      - platform: homeassistant
        event: start
    action:
      - service: tibber.get_prices
        data:
          start: "{{ (today_at() - timedelta(days=1)).strftime('%Y-%m-%d %H:%M:%S') }}"
          end: "{{ (today_at() + timedelta(days=2)).strftime('%Y-%m-%d %H:%M:%S') }}"
        response_variable: prices
    sensor:
      - unique_id: tibber_prices
        name: Tibber prices
        icon: mdi:cash-multiple
        state: "{{ prices.prices.values() | first | selectattr('start_time', '==', now().strftime('%Y-%m-%dT%H:00:00.000+01:00')) | map(attribute='price') | list | last | float }}"
        attributes:
          prices: >
            {% set ns = namespace(prices=[]) %}
            {% for i in prices.prices.values() | first %}
              {% set n = dict(start_time = as_datetime(i.start_time).isoformat(), price = i.price, level = i.level) %}
              {% set ns.prices = ns.prices + [n] %}
            {% endfor %}
            {{ ns.prices }}
        unit_of_measurement: "Euro"
```

Happy to hear if other had this issue as well, and please share your feedback and tips!
