### ISSUE TITLE
time triggers

### ISSUE THREAD

**Issue by rhgiter** [TheFes/cheapest-energy-hours#198]
do i need triggers?

i have noticed that mine triggers in 5 minutes interval

```yaml
  - trigger:
      -  platform: time
         at:
           - '05:58'
           - '06:28'
           - '06:58'
           - '07:28'

           
      -  platform: state
         entity_id: switch.opvaskemaskine
         to: "off"

    sensor:
      - unique_id: f8853830-4-Opvaskemaskine
        name: Opvaskemaskine Start Tid dag
        device_class: timestamp
        state: >
          {% set sensor = 'sensor.energi_data_service' if 'sensor.energi_data_service' | has_value else 'sensor.nordpool_kwh_dk1_dkk_3_10_025' %}    
          {% from "cheapest_energy_hours.jinja" import cheapest_energy_hours %}
          {{ cheapest_energy_hours(sensor=sensor, hours=3, start='06:00', end='17:00', look_ahead=true) }}
```
